default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bookstore_development
  username: imidsac
  password: MOImeme
  host: localhost
  port: 5432


test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production
  username: imidsac
  password: MOImeme
  host: localhost
  port: 5432
